"""
projection.py

This file implements the core Hyperdimensional Computing (HDC)
projection and encoding logic.

Purpose:
- Convert low-dimensional real-valued feature vectors
  into high-dimensional bipolar hypervectors.
- This step replaces learned embeddings or backpropagation.

Key idea:
- Random projections preserve similarity structure
  (refer Johnson–Lindenstrauss lemma).
- High-dimensional bipolar vectors exhibit concentration of measure.
"""

import numpy as np


def generate_random_projection(input_dim, hd_dim, seed):
    """
    Generate a fixed random bipolar projection matrix.

    The projection matrix R has shape:
        R ∈ {−1, +1}^{hd_dim × input_dim}

    Each row corresponds to one hypervector dimension.
    Each column corresponds to one input feature dimension.

    IMPORTANT:
    - This matrix must be FIXED and shared across:
        * all training samples
        * all inference samples
        * all federated clients (if any)
    - Changing R breaks the representation space.

    Parameters
    ----------
    input_dim : int
        Dimensionality of the input feature vector
        (e.g., 128 from the CNN).
    hd_dim : int
        Dimensionality of the hypervector space
        (e.g., 4096).
    seed : int
        Random seed to ensure reproducibility.

    Returns
    -------
    R : np.ndarray, dtype=int8
        Bipolar random projection matrix of shape (hd_dim, input_dim).
    """

    rng = np.random.default_rng(seed)
    
    # Sample each entry independently from {-1, +1}
    R = rng.choice([-1, 1], size=(hd_dim, input_dim))
    
    # Store as int8 to reduce memory footprint
    return R.astype(np.int8)



def encode_hypervector(features, R):
    """
    Encode a real-valued feature vector into a bipolar hypervector.

    Mathematical operation:
        h(x) = sign(R @ x)

    Where:
    - x ∈ ℝ^{input_dim} is the feature vector
    - R ∈ {−1, +1}^{hd_dim × input_dim}
    - h(x) ∈ {−1, +1}^{hd_dim}

    This operation:
    - Projects features into a high-dimensional space
    - Binarizes them using a sign function
    - Produces approximately balanced hypervectors
      (~50% +1, 50% −1)

    Parameters
    ----------
    features : np.ndarray
        1D NumPy array of shape (input_dim,).
    R : np.ndarray
        Random projection matrix generated by
        generate_random_projection().

    Returns
    -------
    h : np.ndarray, dtype=int8
        Bipolar hypervector of shape (hd_dim,).
    """

    # Linear projection into high-dimensional plane
    z = R @ features

    # Apply sign function
    return np.where(z >= 0, 1, -1).astype(np.int8)



